services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # This maps the Docker daemon socket
      - portainer_data:/data # This maps our named volume to the container's data directory

volumes:
  portainer_data:
    name: portainer_data